<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="UTF-8">
    <title>{{ app()->getLocale() === 'ar' ? 'تقرير اتجاه الحركة المخزنية' : 'Inventory Movement Trend Report' }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #222; }
        h2 { margin: 0 0 10px 0; }
        .meta { margin-bottom: 12px; font-size: 11px; color: #555; }
        .footer-meta { margin-top: 16px; font-size: 11px; color: #444; }
        .signatures { margin-top: 18px; width: 100%; }
        .signatures td { width: 50%; border: 0; padding-top: 20px; text-align: center; }
        .sign-line { border-top: 1px solid #888; display: inline-block; min-width: 180px; padding-top: 6px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #ccc; padding: 6px; text-align: center; }
        th { background: #f2f4f8; }
    </style>
</head>
<body>
    <h2>{{ app()->getLocale() === 'ar' ? 'تقرير اتجاه الحركة المخزنية الشهري' : 'Monthly Inventory Movement Trend' }}</h2>
    <div class="meta">
        <div>{{ app()->getLocale() === 'ar' ? 'اسم الشركة' : 'Company Name' }}: {{ $companyName }}</div>
        <div>{{ app()->getLocale() === 'ar' ? 'الفترة' : 'Period' }}: {{ $startDate->toDateString() }} - {{ $endDate->toDateString() }}</div>
        <div>{{ app()->getLocale() === 'ar' ? 'المستودع' : 'Warehouse' }}: {{ $warehouseName ?: (app()->getLocale() === 'ar' ? 'الكل' : 'All') }}</div>
        <div>{{ app()->getLocale() === 'ar' ? 'نوع الحركة' : 'Movement Type' }}: {{ strtoupper($movementType) }}</div>
    </div>

    <table>
        <thead>
        <tr>
            <th>{{ app()->getLocale() === 'ar' ? 'الشهر' : 'Month' }}</th>
            @if($movementType === 'prep' || $movementType === 'transfer' || $movementType === 'waste')
                <th>{{ strtoupper($movementType) }}</th>
            @else
                <th>PREP (Inbound)</th>
                <th>TRANSFER</th>
                <th>WASTE</th>
                <th>Outbound Total</th>
            @endif
        </tr>
        </thead>
        <tbody>
        @foreach($rows as $row)
            <tr>
                <td>{{ $row['month'] }}</td>
                @if($movementType === 'prep')
                    <td>{{ $row['prep'] }}</td>
                @elseif($movementType === 'transfer')
                    <td>{{ $row['transfer'] }}</td>
                @elseif($movementType === 'waste')
                    <td>{{ $row['waste'] }}</td>
                @else
                    <td>{{ $row['prep'] }}</td>
                    <td>{{ $row['transfer'] }}</td>
                    <td>{{ $row['waste'] }}</td>
                    <td>{{ $row['outbound'] }}</td>
                @endif
            </tr>
        @endforeach
        </tbody>
    </table>

    <div class="footer-meta">
        <div>{{ app()->getLocale() === 'ar' ? 'تاريخ الإصدار' : 'Generated At' }}: {{ $generatedAt->format('Y-m-d H:i') }}</div>
        <div>{{ app()->getLocale() === 'ar' ? 'المستخدم' : 'Generated By' }}: {{ $generatedBy }}</div>
    </div>

    <table class="signatures">
        <tr>
            <td><span class="sign-line">{{ app()->getLocale() === 'ar' ? 'اعتماد الإدارة' : 'Management Approval' }}</span></td>
            <td><span class="sign-line">{{ app()->getLocale() === 'ar' ? 'إعداد التقرير' : 'Prepared By' }}</span></td>
        </tr>
    </table>
</body>
</html>
