<?php

namespace Modules\Accounting\Utils;

use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Modules\Accounting\Models\AccountingAccount;
use Modules\Accounting\Models\AccountingAccountTypes;
use Modules\Accounting\Models\AccountsRoting;

class ContractorsAccUtil
{

        public static function default_accounting_route()
    {
        $vat_acc = AccountingAccount::where('gl_code', '214')->first();
        $purchases_acc = AccountingAccount::where('gl_code', '512')->first();
        $sales_acc = AccountingAccount::where('gl_code', '411')->first();
        $discount_acc = AccountingAccount::where('gl_code', '421')->first();

        AccountsRoting::truncate();

        $data = [
            [
                'type' => 'sales_vat_calculation',
                'section' => 'sales',
                'routing_type' => 'liability',
                'account_id' => $vat_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_purchase',
                'section' => 'purchases',
                'routing_type' => 'expense',
                'account_id' => $purchases_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_vat_calculation',
                'section' => 'purchases',
                'routing_type' => 'liability',
                'account_id' => $vat_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'sales_sales',
                'section' => 'sales',
                'routing_type' => 'revenue',
                'account_id' => $sales_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'sales_discount_calculation',
                'section' => 'sales',
                'routing_type' => 'expense',
                'account_id' => $discount_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_discount_calculation',
                'section' => 'purchases',
                'routing_type' => 'expense',
                'account_id' => $discount_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        AccountsRoting::insert($data);
    }

    public static function default_accounting_account_types()
    {
        return  $account_sub_types = [
            [
                'name_en' => 'Current Assets',
                'name_ar' => 'الأصول المتداولة',
                'gl_code' => '11',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'asset',
                'parent_id' => null
            ],
            [
                'name_en' => 'Fixed Assets',
                'name_ar' => 'الأصول الثابتة',
                'gl_code' => '12',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'asset',
                'parent_id' => null
            ],
            [
                'name_en' => 'Current Liabilities',
                'name_ar' => 'الالتزامات المتداولة',
                'gl_code' => '21',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'liabilities',
                'parent_id' => null
            ],
            [
                'name_en' => 'Equity',
                'name_ar' => 'حقوق الملكية',
                'gl_code' => '31',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'equity',
                'parent_id' => null
            ],
            [
                'name_en' => 'Project Revenues',
                'name_ar' => 'إيرادات المشاريع',
                'gl_code' => '41',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'income',
                'parent_id' => null
            ],
            [
                'name_en' => 'Revenues',
                'name_ar' => 'الإيرادات',
                'gl_code' => '42',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'income',
                'parent_id' => null
            ],
            [
                'name_en' => 'Direct costs of projects',
                'name_ar' => 'تكاليف مباشرة للمشاريع',
                'gl_code' => '51',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'expenses',
                'parent_id' => null
            ],
            [
                'name_en' => 'Administrative expenses',
                'name_ar' => 'مصاريف إدارية',
                'gl_code' => '52',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'expenses',
                'parent_id' => null
            ],
            [
                'name_en' => 'Analytical accounts',
                'name_ar' => 'الحسابات التحليلية',
                'gl_code' => '61',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'analytical_accounts',
                'parent_id' => null
            ],






        ];
    }

    public static function Default_Accounts()
    {
        $user_id = Auth::user()->id;

        $current_assets_id = AccountingAccountTypes::where('name_en', 'Current Assets')->first()->id;
        $fixed_assets_id = AccountingAccountTypes::where('name_en', 'Fixed Assets')->first()->id;
        $current_liabilities_id = AccountingAccountTypes::where('name_en', 'Current Liabilities')->first()->id;
        $Equity_id = AccountingAccountTypes::where('name_en', 'Equity')->first()->id;
        $project_revenues_id = AccountingAccountTypes::where('name_en', 'Project Revenues')->first()->id;
        $Revenues_id = AccountingAccountTypes::where('name_en', 'Revenues')->first()->id;
        $direct_costs_projects_id = AccountingAccountTypes::where('name_en', 'Direct costs of projects')->first()->id;
        $administrative_expenses_id = AccountingAccountTypes::where('name_en', 'Administrative expenses')->first()->id;
        $Analytical_accounts_id = AccountingAccountTypes::where('name_en', 'Analytical accounts')->first()->id;

        return [
            [
                'name_en' => 'Land and Buildings',
                'name_ar' => 'أراضي ومباني',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_category'=>'',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '121',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Heavy Equipment and Machinery',
                'name_ar' => 'معدات ثقيلة وآليات',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '122',
                'account_category'=>'',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Engineering Tools and Equipment',
                'name_ar' => 'أدوات ومعدات هندسية',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '123',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Transport Vehicles and Automobiles',
                'name_ar' => 'سيارات نقل ومركبات',
                'account_primary_type' => 'asset',
                'account_category'=>'',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '124',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Furniture and Office Equipment',
                'name_ar' => 'أثاث ومكاتب',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '125',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //-----------
            [
                'name_en' => 'Cash on Hand',
                'name_ar' => 'نقد بالصندوق',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '111',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Cash at Bank',
                'name_ar' => 'نقد بالبنك',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_category'=>'',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '112',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Accounts Receivable',
                'name_ar' => 'العملاء',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '113',
                'account_category'=>'',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Project Receivables',
                'name_ar' => 'ذمم مدينة من مشاريع',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '114',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Prepaid Expenses',
                'name_ar' => 'مصاريف مقدمة',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '115',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Construction Materials and Site Inventory',
                'name_ar' => 'مواد بناء ومخزون موقع',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '116',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //----------
            [
                'name_en' => 'Construction Material Suppliers',
                'name_ar' => 'موردون مواد بناء',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_category'=>'',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'gl_code' => '211',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Subcontractors',
                'name_ar' => 'مقاولون من الباطن',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '212',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Accrued Salaries',
                'name_ar' => 'رواتب مستحقة',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'gl_code' => '213',
                'account_category'=>'',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Due Zakat and Taxes',
                'name_ar' => 'مستحقات زكاة وضريبة',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '214',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Deferred Contract Payments',
                'name_ar' => 'دفعات آجلة لعقود',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '215',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Long-Term Loans',
                'name_ar' => 'القروض طويلة الأجل',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '216',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //------------------
            [
                'name_en' => 'Owner’s Account',
                'name_ar' => 'حساب المالك',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '311',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Retained Earnings',
                'name_ar' => 'الأرباح المحتجزة',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '312',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'name_en' => 'Net Profit / Loss',
                'name_ar' => 'صافي الربح / الخسارة',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '313',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //-------------
            [
                'name_en' => 'Workers and Engineers Salaries',
                'name_ar' => 'رواتب عمال ومهندسين',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $direct_costs_projects_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '511',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Construction Materials',
                'name_ar' => 'مواد بناء',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $direct_costs_projects_id,
                'detail_type_id' => null,
                'gl_code' => '512',
                'account_category'=>'',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Site Operating Expenses',
                'name_ar' => 'مصاريف تشغيل الموقع',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $direct_costs_projects_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '513',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Equipment and Supplies',
                'name_ar' => 'معدات ومستلزمات',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_category'=>'',
                'account_sub_type_id' => $direct_costs_projects_id,
                'detail_type_id' => null,
                'gl_code' => '514',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Subcontractors Expenses',
                'name_ar' => 'مصاريف مقاولين من الباطن',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $direct_costs_projects_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '515',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
                 [
                'name_en' => 'Cost of Goods Sold (COGS)',
                'name_ar' => 'تكلفة مواد البناء',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $direct_costs_projects_id,
                'detail_type_id' => null,
                'gl_code' => '516',
                'account_category'=>'COGS',

                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Administrative Salaries',
                'name_ar' => 'رواتب إدارية',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $administrative_expenses_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '521',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Office Rent',
                'name_ar' => 'إيجارات مكتبية',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $administrative_expenses_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '522',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Communications and Internet',
                'name_ar' => 'اتصالات وإنترنت',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_category'=>'',
                'account_sub_type_id' => $administrative_expenses_id,
                'detail_type_id' => null,
                'gl_code' => '523',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Marketing Expenses',
                'name_ar' => 'مصاريف تسويق',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $administrative_expenses_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '524',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Asset Depreciation',
                'name_ar' => 'إهلاك الأصول',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $administrative_expenses_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '525',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'General Contracting Revenue',
                'name_ar' => 'إيرادات مقاولات عامة',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $project_revenues_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '411',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Subcontracting Revenue',
                'name_ar' => 'إيرادات عقود من الباطن',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $project_revenues_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '412',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => ' Engineering Design Revenue',
                'name_ar' => 'إيرادات تصميم هندسي',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $project_revenues_id,
                'account_category'=>'',
                'detail_type_id' => null,
                'gl_code' => '413',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Operation and Maintenance Revenue',
                'name_ar' => 'إيرادات تشغيل وصيانة',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $project_revenues_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '414',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Project Returns / Discounts',
                'name_ar' => 'مردودات مشاريع / خصومات',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Revenues_id,
                'detail_type_id' => null,
                'gl_code' => '421',
                'account_category'=>'',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Analytical accounts',
                'name_ar' => 'الحسابات التحليلية',
                'account_primary_type' => 'analytical_accounts',
                'account_type' => 'analytical_accounts',
                'account_sub_type_id' => $Analytical_accounts_id,
                'detail_type_id' => null,
                'account_category'=>'',
                'gl_code' => '611',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
    }
}
