<?php

namespace Modules\Accounting\Utils;

use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Modules\Accounting\Models\AccountingAccount;
use Modules\Accounting\Models\AccountingAccountTypes;
use Modules\Accounting\Models\AccountsRoting;

class E_commerceAccUtil
{

    public static function default_accounting_route()
    {
        $vat_acc = AccountingAccount::where('gl_code', '212')->first();
        $purchases_acc = AccountingAccount::where('gl_code', '522')->first();
        $sales_acc = AccountingAccount::where('gl_code', '411')->first();
        $discount_acc = AccountingAccount::where('gl_code', '421')->first();

        AccountsRoting::truncate();

        $data = [
            [
                'type' => 'sales_vat_calculation',
                'section' => 'sales',
                'routing_type' => 'liability',
                'account_id' => $vat_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_purchase',
                'section' => 'purchases',
                'routing_type' => 'expense',
                'account_id' => $purchases_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_vat_calculation',
                'section' => 'purchases',
                'routing_type' => 'liability',
                'account_id' => $vat_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'sales_sales',
                'section' => 'sales',
                'routing_type' => 'revenue',
                'account_id' => $sales_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'sales_discount_calculation',
                'section' => 'sales',
                'routing_type' => 'expense',
                'account_id' => $discount_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_discount_calculation',
                'section' => 'purchases',
                'routing_type' => 'expense',
                'account_id' => $discount_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        AccountsRoting::insert($data);
    }

    public static function default_accounting_account_types()
    {
        return  $account_sub_types = [
            [
                'name_en' => 'Current Assets',
                'name_ar' => 'الأصول المتداولة',
                'gl_code' => '11',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'asset',
                'parent_id' => null
            ],
            [
                'name_en' => 'Fixed Assets',
                'name_ar' => 'الأصول الثابتة',
                'gl_code' => '12',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'asset',
                'parent_id' => null
            ],
            [
                'name_en' => 'Current Liabilities',
                'name_ar' => 'الالتزامات المتداولة',
                'gl_code' => '21',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'liabilities',
                'parent_id' => null
            ],
            [
                'name_en' => 'Liabilities',
                'name_ar' => 'الالتزامات',
                'gl_code' => '22',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'liabilities',
                'parent_id' => null
            ],
            [
                'name_en' => 'Equity',
                'name_ar' => 'حقوق الملكية',
                'gl_code' => '31',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'equity',
                'parent_id' => null
            ],
            [
                'name_en' => 'Sales Revenue',
                'name_ar' => 'إيرادات المبيعات',
                'gl_code' => '41',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'income',
                'parent_id' => null
            ],
            [
                'name_en' => 'Revenues',
                'name_ar' => 'الإيرادات',
                'gl_code' => '42',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'income',
                'parent_id' => null
            ],
            [
                'name_en' => 'Expenses',
                'name_ar' => 'المصاريف',
                'gl_code' => '51',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'expenses',
                'parent_id' => null
            ],
            [
                'name_en' => 'Operating Expenses',
                'name_ar' => 'مصاريف التشغيل',
                'gl_code' => '52',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'expenses',
                'parent_id' => null
            ],
            [
                'name_en' => 'Analytical accounts',
                'name_ar' => 'الحسابات التحليلية',
                'gl_code' => '61',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'analytical_accounts',
                'parent_id' => null
            ],






        ];
    }

    public static function Default_Accounts()
    {
        $user_id = Auth::user()->id;

        $current_assets_id = AccountingAccountTypes::where('name_en', 'Current Assets')->first()->id;
        $fixed_assets_id = AccountingAccountTypes::where('name_en', 'Fixed Assets')->first()->id;
        $current_liabilities_id = AccountingAccountTypes::where('name_en', 'Current Liabilities')->first()->id;
        $liabilities_id = AccountingAccountTypes::where('name_en', 'Liabilities')->first()->id;

        $Equity_id = AccountingAccountTypes::where('name_en', 'Equity')->first()->id;
        $Sales_revenues_id = AccountingAccountTypes::where('name_en', 'Sales Revenue')->first()->id;
        $Revenues_id = AccountingAccountTypes::where('name_en', 'Revenues')->first()->id;
        $Expenses_id = AccountingAccountTypes::where('name_en', 'Expenses')->first()->id;
        $OperatingExpenses_id = AccountingAccountTypes::where('name_en', 'Operating Expenses')->first()->id;
        $Analytical_accounts_id = AccountingAccountTypes::where('name_en', 'Analytical accounts')->first()->id;


        return [
            [
                'name_en' => 'Photography and Packaging Equipment',
                'name_ar' => 'معدات التصوير والتغليف',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '121',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Office Furniture',
                'name_ar' => 'الأثاث المكتبي',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '122',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Computers and Mobile Devices',
                'name_ar' => 'أجهزة الحاسب والهواتف',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_category' => '',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '123',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //-----------
            [
                'name_en' => 'Cash on Hand',
                'name_ar' => 'النقد بالصندوق',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_category' => '',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '111',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Bank Accounts',
                'name_ar' => 'الحسابات البنكية',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '112',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Accounts Receivable (Deferred/Credit Orders)',
                'name_ar' => 'العملاء (طلبات مؤجلة/آجلة)',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '113',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Inventory',
                'name_ar' => 'مخزون البضائع',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'account_category' => 'inventory',
                'detail_type_id' => null,
                'gl_code' => '114',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Prepaid Expenses (Shipping, Advertising)',
                'name_ar' => 'مدفوعات مقدمة (شحن، إعلانات)',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '115',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //----------
            [
                'name_en' => 'Accounts Payable (Suppliers)',
                'name_ar' => 'الموردين',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '211',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Taxes and Government Fees',
                'name_ar' => 'الضرائب والرسوم الحكومية',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_category' => '',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'gl_code' => '212',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Payables to Shipping Companies',
                'name_ar' => 'دفعات مستحقة لشركات الشحن',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '213',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Payables to Payment Gateways',
                'name_ar' => 'مستحقات بوابات الدفع',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '214',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Long-term Loans',
                'name_ar' => 'قروض طويلة الأجل',
                'account_primary_type' => 'liabilities',
                'account_type' => 'liabilities',
                'account_sub_type_id' => $liabilities_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '221',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //------------------
            [
                'name_en' => 'Capital',
                'name_ar' => 'رأس المال',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '311',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Owner’s/Partners’ Equity Account',
                'name_ar' => 'حساب المالك/الشركاء',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '312',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Retained Earnings',
                'name_ar' => 'الأرباح المحتجزة',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '313',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'name_en' => 'Net Profit / Loss',
                'name_ar' => 'صافي الربح / الخسارة',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '314',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //-------------
            [
                'name_en' => ' Cost of Goods Sold (COGS)',
                'name_ar' => 'تكلفة البضاعة المباعة',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $Expenses_id,
                'detail_type_id' => null,
                'account_category' => 'COGS',
                'gl_code' => '511',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Salaries',
                'name_ar' => 'الرواتب',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'gl_code' => '521',
                'account_category' => '',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Shipping and Delivery Expenses',
                'name_ar' => 'مصاريف الشحن والتوصيل',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'gl_code' => '522',
                'account_category' => '',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Storage Expenses',
                'name_ar' => 'مصاريف تخزين',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '523',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Platform Fees and Commissions',
                'name_ar' => 'مصاريف المنصات والعمولات',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '524',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Marketing and Advertising Expenses',
                'name_ar' => 'مصاريف التسويق والإعلانات',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_category' => '',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'gl_code' => '525',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Software and Digital Systems',
                'name_ar' => 'برامج وأنظمة إلكترونية',
                'account_category' => '',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '526',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Content Creation Expenses',
                'name_ar' => 'مصاريف تصوير المحتوى',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_category' => '',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'gl_code' => '527',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Packaging and Wrapping Expenses',
                'name_ar' => 'مصاريف التغليف والتعبئة',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_category' => '',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'gl_code' => '528',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Depreciation of Assets',
                'name_ar' => 'استهلاك الأصول (إهلاك)',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '529',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Inventory Adjustment',
                'name_ar' => 'تسوية المخزون',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'account_category' => 'inventory_adjustment',
                'detail_type_id' => null,
                'gl_code' => '5210',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Website Sales',
                'name_ar' => 'مبيعات الموقع',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_category' => '',
                'account_sub_type_id' => $Sales_revenues_id,
                'detail_type_id' => null,
                'gl_code' => '411',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Marketplace Sales (Salla, Zid, Amazon)',
                'name_ar' => 'مبيعات عبر المتاجر (سلة، زد، أمازون)',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_category' => '',
                'account_sub_type_id' => $Sales_revenues_id,
                'detail_type_id' => null,
                'gl_code' => '412',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => ' Wholesale Sales',
                'name_ar' => 'مبيعات بالجملة',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Sales_revenues_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '413',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Social Media Sales',
                'name_ar' => 'مبيعات عبر وسائل التواصل',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_category' => '',
                'account_sub_type_id' => $Sales_revenues_id,
                'detail_type_id' => null,
                'gl_code' => '414',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Discounts and Promotions',
                'name_ar' => 'خصومات وعروض',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_category' => '',
                'account_sub_type_id' => $Revenues_id,
                'detail_type_id' => null,
                'gl_code' => '421',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Sales Returns',
                'name_ar' => 'مردودات مبيعات',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Revenues_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '422',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Analytical accounts',
                'name_ar' => 'الحسابات التحليلية',
                'account_primary_type' => 'analytical_accounts',
                'account_type' => 'analytical_accounts',
                'account_category' => '',
                'account_sub_type_id' => $Analytical_accounts_id,
                'detail_type_id' => null,
                'gl_code' => '611',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
    }
}