<?php

namespace Modules\Accounting\Utils;

use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Modules\Accounting\Models\AccountingAccount;
use Modules\Accounting\Models\AccountingAccountTypes;
use Modules\Accounting\Models\AccountsRoting;

class GeneralTreeAccUtil
{

    public static function default_accounting_route()
    {
        $vat_acc = AccountingAccount::where('gl_code', '214')->first();
        $purchases_acc = AccountingAccount::where('gl_code', '517')->first();
        $sales_acc = AccountingAccount::where('gl_code', '411')->first();
        $discount_acc = AccountingAccount::where('gl_code', '421')->first();

        AccountsRoting::truncate();

        $data = [
            [
                'type' => 'sales_vat_calculation',
                'section' => 'sales',
                'routing_type' => 'liability',
                'account_id' => $vat_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_purchase',
                'section' => 'purchases',
                'routing_type' => 'expense',
                'account_id' => $purchases_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_vat_calculation',
                'section' => 'purchases',
                'routing_type' => 'liability',
                'account_id' => $vat_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'sales_sales',
                'section' => 'sales',
                'routing_type' => 'revenue',
                'account_id' => $sales_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'sales_discount_calculation',
                'section' => 'sales',
                'routing_type' => 'expense',
                'account_id' => $discount_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_discount_calculation',
                'section' => 'purchases',
                'routing_type' => 'expense',
                'account_id' => $discount_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        AccountsRoting::insert($data);
    }

    public static function default_accounting_account_types()
    {
        return  $account_sub_types = [
            [
                'name_en' => 'Current Assets',
                'name_ar' => 'الأصول المتداولة',
                'gl_code' => '11',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'asset',
                'parent_id' => null
            ],
            [
                'name_en' => 'Fixed Assets',
                'name_ar' => 'الأصول الثابتة',
                'gl_code' => '12',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'asset',
                'parent_id' => null
            ],
            [
                'name_en' => 'Current Liabilities',
                'name_ar' => 'الالتزامات المتداولة',
                'gl_code' => '21',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'liabilities',
                'parent_id' => null
            ],
            [
                'name_en' => 'Long-Term Liabilities',
                'name_ar' => 'الالتزامات طويلة الأجل',
                'gl_code' => '22',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'liabilities',
                'parent_id' => null
            ],
            [
                'name_en' => 'Equity',
                'name_ar' => 'حقوق الملكية',
                'gl_code' => '31',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'equity',
                'parent_id' => null
            ],
            [
                'name_en' => 'Sales / Service Revenues',
                'name_ar' => 'إيرادات المبيعات / الخدمات',
                'gl_code' => '41',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'income',
                'parent_id' => null
            ],
            [
                'name_en' => 'Revenues',
                'name_ar' => 'إيرادات',
                'gl_code' => '42',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'income',
                'parent_id' => null
            ],
            [
                'name_en' => 'Operating Expenses',
                'name_ar' => 'المصاريف التشغيلية',
                'gl_code' => '51',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'expenses',
                'parent_id' => null
            ],
            [
                'name_en' => 'Expenses',
                'name_ar' => 'المصاريف',
                'gl_code' => '52',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'expenses',
                'parent_id' => null
            ],
            [
                'name_en' => 'Analytical accounts',
                'name_ar' => 'الحسابات التحليلية',
                'gl_code' => '61',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'analytical_accounts',
                'parent_id' => null
            ],

        ];
    }

    public static function Default_Accounts()
    {
        $user_id = Auth::user()->id;

        $current_assets_id = AccountingAccountTypes::where('name_en', 'Current Assets')->first()->id;
        $fixed_assets_id = AccountingAccountTypes::where('name_en', 'Fixed Assets')->first()->id;
        $current_liabilities_id = AccountingAccountTypes::where('name_en', 'Current Liabilities')->first()->id;
        $Long_Term_Liabilities_id = AccountingAccountTypes::where('name_en', 'Long-Term Liabilities')->first()->id;
        $Equity_id = AccountingAccountTypes::where('name_en', 'Equity')->first()->id;
        $Sales_Service_revenues_id = AccountingAccountTypes::where('name_en', 'Sales / Service Revenues')->first()->id;
        $Revenues_id = AccountingAccountTypes::where('name_en', 'Revenues')->first()->id;
        $Operating_Expenses_id = AccountingAccountTypes::where('name_en', 'Operating Expenses')->first()->id;
        $expenses_id = AccountingAccountTypes::where('name_en', 'Expenses')->first()->id;
        $Analytical_accounts_id = AccountingAccountTypes::where('name_en', 'Analytical accounts')->first()->id;

        return [
            [
                'name_en' => 'Land',
                'name_ar' => 'أراضي',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '121',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Buildings',
                'name_ar' => 'المباني',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '122',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Machinery and Equipment',
                'name_ar' => 'الآلات والمعدات	',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '123',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Furniture and Fixtures',
                'name_ar' => 'الأثاث والتجهيزات',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '124',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Vehicles',
                'name_ar' => 'وسائل النقل',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '125',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //-----------
            [
                'name_en' => 'Cash on Hand',
                'name_ar' => 'النقد بالصندوق',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '111',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Cash at Bank',
                'name_ar' => 'نقد بالبنك',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '112',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Accounts Receivable',
                'name_ar' => 'العملاء',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '113',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Inventory',
                'name_ar' => 'المخزون',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '114',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Prepaid Expenses',
                'name_ar' => 'مصاريف مقدمة',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '115',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //----------
            [
                'name_en' => 'Accounts Payable',
                'name_ar' => 'الموردين',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'gl_code' => '211',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Short-Term Loans',
                'name_ar' => 'القروض القصيرة الأجل',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'gl_code' => '212',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Accrued Salaries',
                'name_ar' => 'رواتب مستحقة',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'gl_code' => '213',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Due Zakat and Taxes',
                'name_ar' => 'مستحقات زكاة وضريبة',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'gl_code' => '214',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Long-Term Loans',
                'name_ar' => 'القروض طويلة الأجل',
                'account_primary_type' => 'liabilities',
                'account_type' => 'Long_term_liabilities',
                'account_sub_type_id' => $Long_Term_Liabilities_id,
                'detail_type_id' => null,
                'gl_code' => '221',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Owner’s Payables',
                'name_ar' => 'السلف الدائنة من المالك',
                'account_primary_type' => 'liabilities',
                'account_type' => 'Long_term_liabilities',
                'account_sub_type_id' => $Long_Term_Liabilities_id,
                'detail_type_id' => null,
                'gl_code' => '222',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //------------------
            [
                'name_en' => 'Capital',
                'name_ar' => 'رأس المال',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'detail_type_id' => null,
                'gl_code' => '311',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Partners’ Current Account',
                'name_ar' => 'حساب جاري الشركاء',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'detail_type_id' => null,
                'gl_code' => '312',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'name_en' => 'Retained Earnings',
                'name_ar' => 'الأرباح المحتجزة',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'detail_type_id' => null,
                'gl_code' => '313',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Net Profit / Loss',
                'name_ar' => 'صافي الربح / الخسارة',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'detail_type_id' => null,
                'gl_code' => '314',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            //-------------
            [
                'name_en' => 'Rent Expenses',
                'name_ar' => 'الإيجارات',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $Operating_Expenses_id,
                'detail_type_id' => null,
                'gl_code' => '511',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Salaries & Wages',
                'name_ar' => 'الرواتب',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $Operating_Expenses_id,
                'detail_type_id' => null,
                'gl_code' => '512',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Utilities Expenses',
                'name_ar' => 'المرافق',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $Operating_Expenses_id,
                'detail_type_id' => null,
                'gl_code' => '513',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Marketing Expenses',
                'name_ar' => 'مصاريف التسويق',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $Operating_Expenses_id,
                'detail_type_id' => null,
                'gl_code' => '514',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Transportation Expenses',
                'name_ar' => 'مصاريف النقل',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $Operating_Expenses_id,
                'detail_type_id' => null,
                'gl_code' => '515',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Internet & Communication Expenses',
                'name_ar' => 'مصاريف الإنترنت والاتصالات',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $Operating_Expenses_id,
                'detail_type_id' => null,
                'gl_code' => '516',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Purchases',
                'name_ar' => 'مشتريات',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $Operating_Expenses_id,
                'detail_type_id' => null,
                'gl_code' => '517',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Cost of Goods Sold (COGS)',
                'name_ar' => 'تكلفة البضاعة المباعة',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $expenses_id,
                'detail_type_id' => null,
                'gl_code' => '521',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Maintenance Expenses',
                'name_ar' => 'مصاريف الصيانة',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $expenses_id,
                'detail_type_id' => null,
                'gl_code' => '522',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'General and Administrative Expenses (G&A)',
                'name_ar' => 'المصاريف الإدارية والعمومية',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $expenses_id,
                'detail_type_id' => null,
                'gl_code' => '523',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Depreciation Expense',
                'name_ar' => 'الإهلاك',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $expenses_id,
                'detail_type_id' => null,
                'gl_code' => '524',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Local Sales',
                'name_ar' => 'مبيعات محلية',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Sales_Service_revenues_id,
                'detail_type_id' => null,
                'gl_code' => '411',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Export Sales',
                'name_ar' => 'مبيعات تصدير',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Sales_Service_revenues_id,
                'detail_type_id' => null,
                'gl_code' => '412',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => ' Service Revenue',
                'name_ar' => 'إيرادات خدمات',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Sales_Service_revenues_id,
                'detail_type_id' => null,
                'gl_code' => '413',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Sales Discounts',
                'name_ar' => 'خصومات مبيعات',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Revenues_id,
                'detail_type_id' => null,
                'gl_code' => '421',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Sales Returns',
                'name_ar' => 'مردودات مبيعات',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Revenues_id,
                'detail_type_id' => null,
                'gl_code' => '422',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Analytical accounts',
                'name_ar' => 'الحسابات التحليلية',
                'account_primary_type' => 'analytical_accounts',
                'account_type' => 'analytical_accounts',
                'account_sub_type_id' => $Analytical_accounts_id,
                'detail_type_id' => null,
                'gl_code' => '611',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
    }
}
