<?php

namespace Modules\Accounting\Utils;

use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Modules\Accounting\Models\AccountingAccount;
use Modules\Accounting\Models\AccountingAccountTypes;
use Modules\Accounting\Models\AccountsRoting;

class RestaurantCafeAccUtil
{

    public static function default_accounting_route()
    {
        $vat_acc = AccountingAccount::where('gl_code', '213')->first();
        $purchases_acc = AccountingAccount::where('gl_code', '511')->first();
        $sales_acc = AccountingAccount::where('gl_code', '411')->first();
        $discount_acc = AccountingAccount::where('gl_code', '421')->first();

        AccountsRoting::truncate();

        $data = [
            [
                'type' => 'sales_vat_calculation',
                'section' => 'sales',
                'routing_type' => 'liability',
                'account_id' => $vat_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_purchase',
                'section' => 'purchases',
                'routing_type' => 'expense',
                'account_id' => $purchases_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_vat_calculation',
                'section' => 'purchases',
                'routing_type' => 'liability',
                'account_id' => $vat_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'sales_sales',
                'section' => 'sales',
                'routing_type' => 'revenue',
                'account_id' => $sales_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'sales_discount_calculation',
                'section' => 'sales',
                'routing_type' => 'expense',
                'account_id' => $discount_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'purchases_discount_calculation',
                'section' => 'purchases',
                'routing_type' => 'expense',
                'account_id' => $discount_acc?->id,
                'direction' => 'auto_assign',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        AccountsRoting::insert($data);
    }


    public static function default_accounting_account_types()
    {
        return  $account_sub_types = [
            [
                'name_en' => 'Current Assets',
                'name_ar' => 'الأصول المتداولة',
                'gl_code' => '11',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'asset',
                'parent_id' => null
            ],
            [
                'name_en' => 'Fixed Assets',
                'name_ar' => 'الأصول الثابتة',
                'gl_code' => '12',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'asset',
                'parent_id' => null
            ],
            [
                'name_en' => 'Current Liabilities',
                'name_ar' => 'الالتزامات المتداولة',
                'gl_code' => '21',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'liabilities',
                'parent_id' => null
            ],
            [
                'name_en' => 'Equity',
                'name_ar' => 'حقوق الملكية',
                'gl_code' => '31',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'equity',
                'parent_id' => null
            ],
            [
                'name_en' => 'Sales Revenue',
                'name_ar' => 'إيرادات المبيعات',
                'gl_code' => '41',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'income',
                'parent_id' => null
            ],
            [
                'name_en' => 'Revenues',
                'name_ar' => 'الإيرادات',
                'gl_code' => '42',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'income',
                'parent_id' => null
            ],
            [
                'name_en' => 'Cost of Raw Materials',
                'name_ar' => 'تكلفة المواد الأولية',
                'gl_code' => '51',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'expenses',
                'parent_id' => null
            ],
            [
                'name_en' => 'Operating Expenses',
                'name_ar' => 'مصاريف التشغيل',
                'gl_code' => '52',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'expenses',
                'parent_id' => null
            ],
            [
                'name_en' => 'Analytical accounts',
                'name_ar' => 'الحسابات التحليلية',
                'gl_code' => '61',
                'show_balance' => 1,
                'account_type' => 'sub_type',
                'account_primary_type' => 'analytical_accounts',
                'parent_id' => null
            ],






        ];
    }

    public static function Default_Accounts()
    {
        $user_id = Auth::user()->id;

        $current_assets_id = AccountingAccountTypes::where('name_en', 'Current Assets')->first()->id;
        $fixed_assets_id = AccountingAccountTypes::where('name_en', 'Fixed Assets')->first()->id;
        $current_liabilities_id = AccountingAccountTypes::where('name_en', 'Current Liabilities')->first()->id;
        $Equity_id = AccountingAccountTypes::where('name_en', 'Equity')->first()->id;
        $Sales_revenues_id = AccountingAccountTypes::where('name_en', 'Sales Revenue')->first()->id;
        $Revenues_id = AccountingAccountTypes::where('name_en', 'Revenues')->first()->id;
        $CostRawMaterials_id = AccountingAccountTypes::where('name_en', 'Cost of Raw Materials')->first()->id;
        $OperatingExpenses_id = AccountingAccountTypes::where('name_en', 'Operating Expenses')->first()->id;
        $Analytical_accounts_id = AccountingAccountTypes::where('name_en', 'Analytical accounts')->first()->id;

        return [
            [
                'name_en' => 'Buildings (Branch)',
                'name_ar' => 'المباني (الفرع)',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '121',
                'account_category' => '',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Kitchen Equipment',
                'name_ar' => 'معدات المطبخ',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_category' => '',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '122',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Furniture and Decoration',
                'name_ar' => 'الأثاث والديكور',
                'account_primary_type' => 'asset',
                'account_category' => '',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '123',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Electronic Devices (Cashier, POS)',
                'name_ar' => 'الأجهزة الإلكترونية (كاشير، POS)',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_category' => '',
                'account_sub_type_id' => $fixed_assets_id,
                'detail_type_id' => null,
                'gl_code' => '124',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Delivery Vehicles',
                'name_ar' => 'مركبات التوصيل',
                'account_primary_type' => 'asset',
                'account_type' => 'fixed_assets',
                'account_sub_type_id' => $fixed_assets_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '125',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //-----------
            [
                'name_en' => 'Cash on Hand',
                'name_ar' => 'الصندوق',
                'account_category' => '',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '111',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Bank Accounts',
                'name_ar' => 'الحسابات البنكية',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '112',
                'status' => 'active',
                'account_category' => '',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Customers (Credit Sales)',
                'name_ar' => 'العملاء (طلبات آجلة)',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '113',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Raw Material Inventory (Food & Beverages)',
                'name_ar' => 'مخزون المواد الخام (مأكولات ومشروبات)',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '114',
                'account_category' => 'inventory',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Prepaid Expenses',
                'name_ar' => 'مصاريف مدفوعة مقدماً',
                'account_primary_type' => 'asset',
                'account_type' => 'current_assets',
                'account_category' => '',
                'account_sub_type_id' => $current_assets_id,
                'detail_type_id' => null,
                'gl_code' => '115',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //----------
            [
                'name_en' => 'Suppliers (Provisions, Beverages, Services)',
                'name_ar' => 'الموردين (مؤن، مشروبات، خدمات)',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '211',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Accrued Salaries',
                'name_ar' => 'رواتب مستحقة',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '212',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Taxes and Zakat',
                'name_ar' => 'الضرائب والزكاة',
                'account_primary_type' => 'liabilities',
                'account_category' => '',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'gl_code' => '213',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Deferred Rent Payments',
                'name_ar' => 'دفعات آجلة للإيجار',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_category' => '',
                'account_sub_type_id' => $current_liabilities_id,
                'detail_type_id' => null,
                'gl_code' => '214',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Long-term Loans',
                'name_ar' => 'قروض طويلة الأجل',
                'account_primary_type' => 'liabilities',
                'account_type' => 'current_liabilities',
                'account_sub_type_id' => $current_liabilities_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '215',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //------------------
            [
                'name_en' => 'Capital',
                'name_ar' => 'رأس المال',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_category' => '',
                'account_sub_type_id' => $Equity_id,
                'detail_type_id' => null,
                'gl_code' => '311',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Owner’s Account',
                'name_ar' => 'حساب المالك',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_category' => '',
                'account_sub_type_id' => $Equity_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '312',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Retained Earnings',
                'name_ar' => 'الأرباح المحتجزة',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '313',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'name_en' => 'Net Profit / Loss',
                'name_ar' => 'صافي الربح / الخسارة',
                'account_primary_type' => 'equity',
                'account_type' => 'equity',
                'account_sub_type_id' => $Equity_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '314',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            //-------------
            [
                'name_en' => 'Cost of Meat and Vegetables',
                'name_ar' => 'تكلفة اللحوم والخضروات',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $CostRawMaterials_id,
                'detail_type_id' => null,
                'gl_code' => '511',
                'account_category' => 'COGS',

                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Cost of Beverages',
                'name_ar' => 'تكلفة المشروبات',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $CostRawMaterials_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '512',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Cost of Packaging and Presentation',
                'name_ar' => 'تكلفة التغليف والتقديم',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $CostRawMaterials_id,
                'detail_type_id' => null,
                'gl_code' => '513',
                'account_category' => '',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Inventory Adjustment',
                'name_ar' => 'تسوية المخزون',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $CostRawMaterials_id,
                'account_category' => 'inventory_adjustment',
                'detail_type_id' => null,
                'gl_code' => '514',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Salaries and Wages',
                'name_ar' => 'الرواتب والأجور',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '521',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Branch Rent',
                'name_ar' => 'إيجار الفرع',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '522',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Electricity and Water',
                'name_ar' => 'كهرباء ومياه',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'account_category' => '',
                'detail_type_id' => null,
                'gl_code' => '523',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Maintenance Expenses',
                'name_ar' => 'مصاريف الصيانة',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '524',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Delivery Expenses',
                'name_ar' => 'مصاريف التوصيل',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'gl_code' => '525',
                'account_category' => '',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Systems and Software',
                'name_ar' => 'أنظمة وبرمجيات',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'gl_code' => '526',
                'status' => 'active',
                'account_category' => '',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Asset Depreciation',
                'name_ar' => 'استهلاك الأصول (إهلاك)',
                'account_primary_type' => 'expenses',
                'account_type' => 'expenses',
                'account_sub_type_id' => $OperatingExpenses_id,
                'detail_type_id' => null,
                'gl_code' => '527',
                'account_category' => '',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Food Sales',
                'name_ar' => 'مبيعات الطعام',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Sales_revenues_id,
                'detail_type_id' => null,
                'gl_code' => '411',
                'account_category' => '',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Beverage Sales',
                'name_ar' => 'مبيعات المشروبات',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Sales_revenues_id,
                'detail_type_id' => null,
                'gl_code' => '412',
                'status' => 'active',
                'account_category' => '',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => ' Delivery Orders',
                'name_ar' => 'طلبات التوصيل',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Sales_revenues_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '413',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Pre-orders / Reservations',
                'name_ar' => 'الطلب المسبق / الحجوزات',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Sales_revenues_id,
                'detail_type_id' => null,
                'gl_code' => '414',
                'account_category' => '',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name_en' => 'Sales Discounts',
                'name_ar' => 'خصومات على المبيعات',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Revenues_id,
                'detail_type_id' => null,
                'gl_code' => '421',
                'status' => 'active',
                'account_category' => '',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Sales Returns',
                'name_ar' => 'مردودات مبيعات',
                'account_primary_type' => 'income',
                'account_type' => 'income',
                'account_sub_type_id' => $Revenues_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '422',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name_en' => 'Analytical accounts',
                'name_ar' => 'الحسابات التحليلية',
                'account_primary_type' => 'analytical_accounts',
                'account_type' => 'analytical_accounts',
                'account_sub_type_id' => $Analytical_accounts_id,
                'detail_type_id' => null,
                'account_category' => '',
                'gl_code' => '611',
                'status' => 'active',
                'created_by' => $user_id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
    }
}